import './globals.css'


export const metadata = {
  title: 'JS-Mastery',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='min-h-screen bg-black-100'>{children}</body>
    </html>
  )
}
